database:
  schemas:
    public:
      tag_and_object:
        index:
          path: /tmp/dream/test/TEST_NAME/tables/tag_and_object/index.idx
        data_pool:
          fixed:
            path: /tmp/dream/test/TEST_NAME/tables/tag_and_object/data.dat
            container_size: 32
      object_and_tag:
        index:
          path: /tmp/dream/test/TEST_NAME/tables/object_and_tag/index.idx
        data_pool:
          fixed:
            path: /tmp/dream/test/TEST_NAME/tables/object_and_tag/data.dat
            container_size: 32
      object:
        index:
          path: /tmp/dream/test/TEST_NAME/tables/object/index.idx
        data_pool:
          fixed:
            path: /tmp/dream/test/TEST_NAME/tables/object/data.dat
            container_size: 16
  log:
    path: /tmp/dream/test/TEST_NAME/log.dat
    checkpoint_on_size: 8 GB
